name: PlyoMetrics
description: "High-speed video jump testing for coaches and athletes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  fl_chart: ^0.70.2
  camera: ^0.11.1
  video_player: ^2.9.3
  shared_preferences: ^2.3.4
  intl: ^0.20.2
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  ffmpeg_kit_flutter_new: ^4.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
